### ISSUE TITLE
Writing issue with Katapult

### ISSUE THREAD

**Issue by mpx1986** [mlee12382/Klipper-Flashing-Script#1]
python3 ~/Katapult/scripts/flashtool.py -i can0 -u 39c374a93450 -r

its incorrect 

the right writing of the path is

python3 ~/katapult/scripts/flashtool.py -i can0 -u 39c374a93450 -r

katapult is writen with a small k

**Comment by mlee12382** [comment]
Fixed, I'm still on an older setup using CanBoot paths. Thanks for the correction.

**Comment by mpx1986** [comment]
it´s realy good script
